import os

import ee
import geopandas as gpd
import numpy as np
import xarray as xr
from scipy.cluster.hierarchy import fcluster, linkage
from typing import Any


def initialize_ee(project_name: str | None = None) -> None:
    """
    Attempts to initialize Earth Engine. Falls back to authentication if required.

    Args:
        project_name: Optional explicit project name. If not provided,
            it attempts to read the 'GOOGLE_CLOUD_PROJECT' environment variable.
    """
    project = project_name or os.environ.get("GOOGLE_CLOUD_PROJECT")

    if not project:
        raise ValueError(
            "Earth Engine project name not provided. Pass it to the function "
            "or set the 'GOOGLE_CLOUD_PROJECT' environment variable."
        )

    try:
        ee.Initialize(project=project)
    except ee.ee_exception.EEException:
        ee.Authenticate()
        ee.Initialize(project=project)


def cluster_geometries(
    gdf: gpd.GeoDataFrame, max_distance_deg: float = 2.0
) -> gpd.GeoDataFrame:
    """
    Cluster geometries in a GeoDataFrame based on their distance.

    Args:
        gdf: GeoDataFrame containing the shapes to cluster.
        max_distance_deg: Maximum separation distance to belong to the same cluster (in degrees).

    Returns:
        A copy of the GeoDataFrame with an assigned 'cluster_id' column.
    """
    if len(gdf) <= 1:
        gdf_clustered = gdf.copy()
        gdf_clustered["cluster_id"] = [1] * len(gdf)
        return gdf_clustered

    centroids = gdf.geometry.centroid
    coords = np.column_stack((centroids.x, centroids.y))

    Z = linkage(coords, method="single", metric="euclidean")

    labels = fcluster(Z, t=max_distance_deg, criterion="distance")

    gdf_clustered = gdf.copy()
    gdf_clustered["cluster_id"] = labels
    return gdf_clustered


def enforce_zarr_chunk_uniformity(ds: xr.Dataset, chunks: Any) -> xr.Dataset:
    """
    Cleans up encoding and forces uniform chunking on an xarray Dataset to ensure
    compatibility with the Zarr backend. This is particularly necessary for datasets
    generated by xee/Earth Engine, which may have irregular edge chunks.

    Args:
        ds: The input Dataset.
        chunks: The chunking scheme (e.g., "auto" or a dictionary).

    Returns:
        The rechunked Dataset with sanitized encoding.
    """
    # clear encoding that interferes with Zarr chunking rules
    for var in ds.variables:
        ds[var].encoding.pop("chunks", None)
        ds[var].encoding.pop("preferred_chunks", None)

    # force rechunking to ensure uniform boundaries for Zarr
    # Dask's "auto" can sometimes preserve irregular edges from xee
    if chunks == "auto":
        uniform_chunks = {}
        for dim in ds.dims:
            for var in ds.variables:
                if dim in ds[var].dims and ds[var].chunks is not None:
                    dim_idx = ds[var].dims.index(dim)
                    first_chunk = ds[var].chunks[dim_idx][0]
                    uniform_chunks[dim] = first_chunk
                    break
        if uniform_chunks:
            return ds.chunk(uniform_chunks)

    return ds.chunk(chunks)
